# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afa459cdacf5d323b684c002eeb4451eb83bd38044dcc5605937c4da689fa660a2f0ef4b1cd9a37308011b7232620f66d92adddc92d1515205e7370a88a4269

test:
  secret_key_base: 2ce6524e48f373250748933b47be3213586c5c0af424faca96d444937f2a7041af05e9a1d38c153e799dd758f91b53228154b9a558911e448849270844d1fbd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
